### PR TITLE
Add Queries.sql

### PR DESCRIPTION
**Pull request by jerry3128**

### CODE REVIEW

**Comment by Johnnybyzhang** [comment]
@yorrickzzy Please review this

**Review by Johnnybyzhang — CHANGES_REQUESTED** [review]
This should belong to another PR, please remove this from here and create a new PR

**Comment by jerry3128** [comment]
Done, remove the 'EndPoint' Part

**Comment by Johnnybyzhang** [comment]
LGTM, @yorrickzzy can merge as you see fit

**Review by Johnnybyzhang — APPROVED** [review]

**Pull request merged**
